# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gradio-blocks',
                'doc_host': 'https://lukexyz.github.io',
                'git_url': 'https://github.com/lukexyz/gradio-blocks',
                'lib_path': 'gradio_blocks'},
  'syms': {'gradio_blocks.charts': {'gradio_blocks.charts.get_sample': ('charts.html#get_sample', 'gradio_blocks/charts.py')}}}
