# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gradio-blocks',
                'doc_host': 'https://lukexyz.github.io',
                'git_url': 'https://github.com/lukexyz/gradio-blocks',
                'lib_path': 'gradio_blocks'},
  'syms': {'gradio_blocks.core': {'gradio_blocks.core.foo': ('core.html#foo', 'gradio_blocks/core.py')}}}
